app:
  out_dir: out
  logs_dir: logs
  cache_dir: cache
api_limits:
  finnhub:
    per_second: 30
    per_minute: 60
    reserve: 2
  yahoo:
    per_second: 5
    per_minute: 20
    reserve: 2
  pytrends:
    per_second: 2
    per_minute: 10
    reserve: 2
normalization:
  winsor_p_low: 0.05
  winsor_p_high: 0.95
  min_universe_for_robust: 5
  clip_min: -5.0
  clip_max: 5.0
universe:
  min_price: 5.0
  dollar_volume_floor: 10000000.0
  horizon_days: 2
  session: amc
  min_dollar_vol: 5000000.0
  max_names: 60
  sector_allowlist:
  - Information Technology
  - Consumer Discretionary
  - Health Care
selection:
  risk_floor_sigma_g: -2.0
  risk_floor_tau_g: -2.0
  score_threshold: 0.0
  max_names: 30
  max_per_sector: 10
etfs:
  sectors:
    Information Technology: XLK
    Consumer Discretionary: XLY
    Financials: XLF
    Industrials: XLI
    Energy: XLE
    Health Care: XLV
    Utilities: XLU
    Materials: XLB
    Real Estate: XLRE
    Communication Services: XLC
    Consumer Staples: XLP
    _default: SPY
features:
  sector_etfs:
  - XLK
  - XLY
  - XLF
  - XLI
  - XLE
  - XLV
  - XLU
  - XLB
  - XLRE
  - XLC
  - XLP
  peer_drift_window_days: 5
  macro_vix: true
  macro_yields: false
  search_index: true
  trends_allowlist:
  - AAPL
  - MSFT
  - AMZN
validation:
  min_rows: 1
  min_coverage: 0.8
