base:
  m: 0.30
  v: 0.20
  s: 0.10
  a: 0.10
  sigma: -0.05
  tau: -0.05
  cal: -0.05      # NEW: calendar density (crowding)
  srm: 0.10       # NEW: sector relative momentum
  peer: 0.08      # NEW: peer earnings drift
  etff: 0.04      # NEW: sector ETF "flow" proxy
  vix_risk: -0.04 # NEW: macro VIX risk
  trend: 0.02     # NEW: search interest

multipliers:
  _default: { m: 1.0, v: 1.0, s: 1.0, a: 1.0, sigma: 1.0, tau: 1.0, cal: 1.0, srm: 1.0, peer: 1.0, etff: 1.0, vix_risk: 1.0, trend: 1.0 }

caps:
  exp_min: 0.3
  exp_max: 3.0
