# Global base exponents
base:
  wm: 0.3      # Momentum
  wv: 0.2      # Volume/Liquidity
  ws: 0.2      # Sector/Peer alignment
  wa: 0.3      # Analyst/estimate trend
  w_sigma: 0.5 # Volatility risk (as goodness when inverted)
  w_tau: 0.5   # Tail/crowding/liquidity risk (as goodness when inverted)

# Sector multipliers (applied to base exponents)
multipliers:
  Consumer Discretionary: { m: 1.3, v: 1.2, s: 1.3, a: 1.1, tau: 1.0 }
  Industrials:            { m: 1.2, v: 1.1, s: 1.3, a: 1.0, tau: 1.0 }
  Materials:              { m: 1.1, v: 1.2, s: 1.2, a: 1.0, tau: 1.2 }
  Energy:                 { m: 1.1, v: 1.2, s: 1.1, a: 0.9, tau: 1.3 }
  Financials:             { m: 0.9, v: 1.0, s: 1.2, a: 1.4, tau: 1.0 }
  Information Technology: { m: 1.1, v: 1.0, s: 1.1, a: 1.3, tau: 1.2 }
  Communication Services: { m: 0.7, v: 0.8, s: 0.8, a: 0.8, tau: 1.4 }
  Health Care:            { m: 0.7, v: 0.8, s: 0.8, a: 0.8, tau: 1.4 }
  Consumer Staples:       { m: 0.7, v: 0.8, s: 0.8, a: 0.8, tau: 1.4 }
  Utilities:              { m: 0.7, v: 0.8, s: 0.8, a: 0.8, tau: 1.4 }
  Real Estate:            { m: 0.7, v: 0.8, s: 0.8, a: 0.8, tau: 1.4 }
  _default:               { m: 1.0, v: 1.0, s: 1.0, a: 1.0, tau: 1.0 }

caps:
  exp_min: 0.10
  exp_max: 0.80
